version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Deps
          command:
            pip install -r requirements.txt
      - run:
          command: python ./test.py
          name: Run Normal Test
      - run:
          name: Run Coverage Test
          command: coverage run ./test.py && codecov -t c672a594-7609-4727-8b71-ab391150d167

workflows:
  main:
    jobs:
      - build-and-test
