version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Deps
          command:
            pip install -r requirements.txt
      - run:
          command: ./test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
